package uned.pfg.main;

import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import uned.pfg.bean.Pedido;
import uned.pfg.logica.ServicioPedido;

public class Gui_Pedido extends JFrame{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabla;
    private DefaultTableModel modelo;
    private Object [][]filas;
    private Object [] columnas = {"ID PEDIDO", "DISTRIBUIDOR","FECHA REALIZACION","FECHA ENVIO", "ESTADO"};
	/**
     * Creates new form guiPedidos
     */
    public Gui_Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        
        modelo = new DefaultTableModel(filas, columnas);
        
        tabla.setModel(modelo);
        scroll.setViewportView(tabla);
        
        contruirTabla();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

	private void contruirTabla() {

		
		ServicioPedido service = new ServicioPedido();
		
		List<Pedido> list = service.parseXMLtoList();
		
		//System.out.println(list.size());
		
		Iterator<Pedido> it = list.iterator();
		
		SimpleDateFormat formatter = new SimpleDateFormat("yyyy-mm-dd");
		while(it.hasNext()) {
			
			Pedido p = it.next();
			
            Object [] row = {p.getId_pedido(), p.getId_distribuidor(), formatter.format(p.getFecha_entrada()),
            		formatter.format(p.getFecha_envio()), p.getEstado()};
            
            modelo.addRow(row);
		}
	}



}
