package uned.pfg.main;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import uned.pfg.bean.Pedido;
import uned.pfg.logica.ServicioPedido;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

public class JFrameEjemplo extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form NewJFrame1
     */
    public JFrameEjemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();


        jPanel1_1 = new javax.swing.JPanel();
        jScrollPane1_1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        
        modelo = new DefaultTableModel(filas, columnas);
        
        jTable1.setModel(modelo);
        jScrollPane1_1.setViewportView(jTable1);
        
        contruirTabla();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1_1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap(34, Short.MAX_VALUE)
        			.addComponent(jScrollPane1_1, GroupLayout.PREFERRED_SIZE, 614, GroupLayout.PREFERRED_SIZE)
        			.addGap(21))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1_1, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1_1.setLayout(jPanel1Layout);

        jButton1.setText("Ver Articulos");
        
        lblNewLabel = new JLabel("Seleccione un Pedido y pulse en el boton para ver los articulos");
        
        lblNewLabel_1 = new JLabel("PEDIDO SELECCIONADO =>");
        
        lblNewLabel_2 = new JLabel("new label");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(421)
        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(84, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(39, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 345, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
        			.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblNewLabel_2)
        			.addGap(107))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1_1, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
        			.addGap(3)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel_1)
        				.addComponent(lblNewLabel_2)
        				.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton1)
        			.addContainerGap(157, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
        
        jTable1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				
				System.out.println(jTable1.rowAtPoint(e.getPoint()));
				
				int entero = jTable1.rowAtPoint(e.getPoint());
				lblNewLabel_2.setText(String.valueOf(jTable1.getValueAt(entero, 0)));
				
			}
		});
    }// </editor-fold>                        

                                   

/*
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEjemplo().setVisible(true);
            }
        });
    }*/
    
	private void contruirTabla() {

		
		ServicioPedido service = new ServicioPedido();
		
		List<Pedido> list = service.parseXMLtoList();
		
		//System.out.println(list.size());
		
		Iterator<Pedido> it = list.iterator();
		
		SimpleDateFormat formatter = new SimpleDateFormat("yyyy-mm-dd");
		while(it.hasNext()) {
			
			Pedido p = it.next();
			
            Object [] row = {p.getId_pedido(), p.getId_distribuidor(), formatter.format(p.getFecha_entrada()),
            		formatter.format(p.getFecha_envio()), p.getEstado()};
            
            modelo.addRow(row);
		}
	}

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private JPanel jPanel1_1;
    private javax.swing.JScrollPane jScrollPane1;
    private JScrollPane jScrollPane1_1;
    private javax.swing.JTable jTable1;
    private DefaultTableModel modelo;
    private Object [][]filas;
    private Object [] columnas = {"ID PEDIDO", "DISTRIBUIDOR","FECHA REALIZACION","FECHA ENVIO", "ESTADO"};
    private JLabel lblNewLabel;
    private JLabel lblNewLabel_1;
    private JLabel lblNewLabel_2;
    // End of variables declaration                 
}
