package uned.pfg.main;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.JOptionPane;

import uned.pfg.bean.Distribuidor;
import uned.pfg.logica.ServicioEliminarDistribuidor;
import uned.pfg.logica.ServicioObtenerDistribuidor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Windows
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form gui_alta_articulos
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        infoNombreArt = new javax.swing.JLabel();
        infoFecha = new javax.swing.JLabel();
        infoNuevoArticulos = new javax.swing.JLabel();
        nombreArt = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        precio = new javax.swing.JTextField();
        infoPrecio = new javax.swing.JLabel();
        euro = new javax.swing.JLabel();
        enviar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        infoBajaDistribuidor = new javax.swing.JLabel();
        distribuidores = new javax.swing.JComboBox<String>();
        eliminarDistribuidor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        consultarPedido = new javax.swing.JButton();
        nuevoPedido = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        listaDis = new ArrayList<Distribuidor>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VENTAS ");

        infoNombreArt.setText("NOMBRE DEL ARTÍCULO");

        infoFecha.setText("FECHA DE ENTRADA");

        infoNuevoArticulos.setText("ALTA NUEVOS ARTICULOS ");
        infoNuevoArticulos.setMaximumSize(new java.awt.Dimension(131, 20));
        infoNuevoArticulos.setMinimumSize(new java.awt.Dimension(131, 20));

        infoPrecio.setText("PRECIO POR UNIDAD");

        euro.setText("€");

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        infoBajaDistribuidor.setText("BAJA DISTRIBUIDOR");

        distribuidores.setModel(new javax.swing.DefaultComboBoxModel<String>(Distribuidores()));

        eliminarDistribuidor.setText("Eliminar Distribuidor");
        eliminarDistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDistribuidorActionPerformed(evt);
            }
        });

        consultarPedido.setText("CONSULTAR PEDIDOS");
        consultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPedidoActionPerformed(evt);
            }
        });

        nuevoPedido.setText("NUEVO PEDIDO");
        nuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPedidoActionPerformed(evt);
            }
        });

        stock.setText("ALMACEN");
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nuevoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoNombreArt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(infoPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                        .addComponent(infoFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreArt)
                                    .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(euro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(distribuidores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminarDistribuidor, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(infoNuevoArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoBajaDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoNuevoArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoBajaDistribuidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoNombreArt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distribuidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enviar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(euro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarDistribuidor)))))
        );

        pack();
    }// </editor-fold>                        

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
    }                                      

    private void nuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
    	Gui_NuevoPedido nuevopedido = new Gui_NuevoPedido();
    	nuevopedido.setVisible(true);
    }                                           

    private void consultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {                                                

    	new Gui_Pedido().setVisible(true);
    }                                               

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
    	
    	
    }                                      

    private void eliminarDistribuidorActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        
    	
    	String seleccion = distribuidores.getSelectedItem().toString();
    	
    	if(seleccion.equals("Selec. Distribuidor")) {
			   JOptionPane.showMessageDialog(null, "Debe marcar algun distribuidor a eliminar..."
					   , "Ventas", 2);
    		
    	}else {
    		
    		int confirmar = JOptionPane.showConfirmDialog(null, "¿Esta segudo de eliminar el"
    				+ " el distribuidor " + seleccion + " ?");
    		
    		if(JOptionPane.OK_OPTION == confirmar) {
    			
    			String result = new ServicioEliminarDistribuidor(seleccion).getResultado();
            	if(result.equals("exito")) {
            		
     			   JOptionPane.showMessageDialog(null, "DISTRIBUIDOR ELIMINADO"
    					   , "Ventas", 1);
            	}else if(result.equals("error")) {
            		
      			   JOptionPane.showMessageDialog(null, "NO ES POSIBLE BORRAR EL DISTRIBUIDOR."
      			   		+ " Posee pedidos aun pendientes de confirmar"
    					   , "Ventas", 2);
            	}else {
            		
       			   JOptionPane.showMessageDialog(null, "Ups..no es posible conectar con el servidor..."
       					   , "Ventas", 2);
            	}
        		
            	distribuidores.setModel(new javax.swing.DefaultComboBoxModel<String>(Distribuidores()));
    		}
    		
    		
    	}
    	


    }
    
    private String[] Distribuidores() {
 	   
 	   ServicioObtenerDistribuidor servicio = new ServicioObtenerDistribuidor();
 	   listaDis = servicio.parseXMLtoList();
 	   
 	   String[] distribuidores = new String[listaDis.size()+1];
 	   
 	   Iterator<Distribuidor> it = listaDis.iterator();
 	   distribuidores[0] = "Selec. Distribuidor";
 	   int i =1;
 	   while(it.hasNext()) {
 		   
 		   Distribuidor d = it.next();
 		   distribuidores[i] = d.getNombre();
 		   i++;
 	   }
 	   
 	   
 	   
 	return distribuidores;
 	   
 	   
    }

   

    // Variables declaration - do not modify                     
    private javax.swing.JButton borrar;
    private javax.swing.JButton consultarPedido;
    private javax.swing.JComboBox<String> distribuidores;
    private javax.swing.JButton eliminarDistribuidor;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel euro;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel infoBajaDistribuidor;
    private javax.swing.JLabel infoFecha;
    private javax.swing.JLabel infoNombreArt;
    private javax.swing.JLabel infoNuevoArticulos;
    private javax.swing.JLabel infoPrecio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreArt;
    private javax.swing.JButton nuevoPedido;
    private javax.swing.JTextField precio;
    private javax.swing.JButton stock;
    private List<Distribuidor> listaDis;
    // End of variables declaration                   
}
